project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "EDA Final Project on TEDS"
  author:
    - Qinghui Zeng (qz2548)
    - Runzhou Liu (rl3462)
  repo-url: https://github.com/QHCeng/EDA_Final
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


